### PR TITLE
Add Python3 support

### PR DESCRIPTION
**Pull request by pbauer**

### CODE REVIEW

**Comment by mauritsvanrees** [comment]
@pbauer Do you want to have another go at Python 3 and 5.2 support? I have meanwhile fixed Travis, so that should help.
`bin/code-analysis` complains about `isort`, but I did not want to fix that on master, because it might make merging this PR harder.

**Comment by mauritsvanrees** [comment]
@pbauer I have merged master into your python3 branch, and have added a few more fixes.
For me, this is ready to merge. Should still work on Plone 4.3-5.2.
Can you have a look?
Or @tschorr?

**Comment by tschorr** [comment]
lgtm

**Comment by mauritsvanrees** [comment]
I have moved the changelog entry to the right header. It was wrongly placed after merge.

@tschorr Can you make a new release? Call it 1.0.0 I would say.
Or I can do it, I have the collective pypi account which can do that.

**Comment by tschorr** [comment]
@mauritsvanrees feel free to do the PyPI release.

**Comment by mauritsvanrees** [comment]
I have released 1.0.0.

**Pull request merged**
