### PR TITLE
Don't let statistics fail on catalog out of sync

### PR DESCRIPTION
**Pull request by tomgross**

### CODE REVIEW

**Comment by tschorr** [comment]
This is basically the same as approach as in #13, (6f5dd5d9ebc264968d6b844cc1c634eb8472dafb).
I'm still reluctant to do this, see my previous comment: https://github.com/collective/collective.revisionmanager/pull/13#issuecomment-270096187

**Comment by tschorr** [comment]
Closing this following our conversation this morning.

**Comment by hvelarde** [comment]
you left a stale branch behind.

**Comment by tschorr** [comment]
@hvelarde yes.

**Pull request closed without merging**
